# Generated by Django 6.0 on 2026-02-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_make_exam_times_optional'),
        ('accounts', '0009_alter_studentexam_unique_together'),
    ]

    operations = [
    ]
